### ISSUE TITLE
Howto for Wildfly (non-swarm)

### ISSUE THREAD

**Issue by t1** [wildfly-extras/wildfly-microprofile-config#19]
I will try to figure this out myself and add it to the readme, but maybe somebody can give me the right pointer: I understand that it builds a feature-pack which are concept of how Wildfly itself is built. But how do I add it to an existing installation?
BTW: I found @jmesnil's [blog article](http://jmesnil.net/weblog/2017/07/27/eclipse-microprofile-config-10/) very helpful.

**Comment by jmesnil** [comment]
feature-packs are to build distribution of WildFly and not intended for updating existing installations.

Having said that, there are a few steps to install the microprofile-config in an existing installation.
1. Download and unzip the distribution from wildfly-microprofile-config-dist maven ZIP artifact (e.g. http://central.maven.org/maven2/org/wildfly/wildfly-microprofile-config-dist/1.1.1/)
2. copy the `modules` directory from the unzipped archive to the existing installation's `module` directory.
3. update the standalone configuration to install the `microprofile-config` extension and subsystem:

```
<extension module="org.wildfly.extension.microprofile.config"/>
...
<subsystem xmlns="urn:wildfly:microprofile-config:1.0"/>
```

**Comment by t1** [comment]
@jmesnil: Thanks for the detailed instructions. I've tried them and added instructions to the README. Is that okay for you?

**Comment by jmesnil** [comment]
thanks!
