### ISSUE TITLE
Support property conversion for environment variables

### ISSUE THREAD

**Issue by jmesnil** [wildfly-extras/wildfly-microprofile-config#36]
Some OS does not allow dot `.` in the name of their env variables and use underscore `_`.
Env variables also often use upper case for their names.

If a Java application uses a `num.size` config property, the user can not add a `num.size` environment variable to provide a value.

For properties coming from the EnvConfigSource (and only that one), we should support some name conversion:
For a property named `num.size`:
1. check if there is an env variable named `num.size` [exact match]
2. if that's not the case, check if there is an env variable named `num_size` [replaced dots by underscores]
3. if that's not the case, check if there is an env variable named `NUM_SIZE` [replaced dots by underscores + upper case]

**Comment by jmesnil** [comment]
@pilhuhn Would that solve your use case for mp-metrics?

I plan to push to add it to the mp-config spec but nothing precludes to provides this improvement to our mp-config implementation already.

**Comment by pilhuhn** [comment]
Yes, 3) is what I was looking for. Thank you

**Comment by smoyer64** [comment]
I see that this isn't in the 1.2.1 implementation (provided by wildfly-swarm-bom 2018-2-0) ... is it waiting for the specification change expected with Microprofile-Config 1.3?  Also note that in Swarm it's currently problematic when trying to use configuration properties that contain dashes (https://issues.jboss.org/browse/SWARM-1528).

**Comment by jmesnil** [comment]
@smoyer64 you are correct.

1.2.1 release was to fix some TCK challenges. 
This new feature will be available with mp config 1.3.

**Comment by smoyer64** [comment]
Thanks for the confirmation ... I'm providing links to your PR's code as well as the conversation on the MP-CONFIG specification as an additional comment to SWARM-1528.  It looks like things are aligning very favorably (if we can just do something about the dashes in the Swarm configuration property names)!

**Comment by smoyer64** [comment]
Added https://github.com/eclipse/ConfigJSR/issues/53 after further discussion on SWARM-1528 to address the conversion of configuration property names that contain dashes to environment variable names.
