### ISSUE TITLE
Injection of Optional<String> is returning ConfigProperty.UNCONFIGURED_VALUE when configuration value is missing

### ISSUE THREAD

**Issue by starksm64** [wildfly-extras/wildfly-microprofile-config#43]
See this issue that I filed to add a missing TCK test:
https://github.com/eclipse/microprofile-config/issues/336

I saw the problem of the ConfigProperty.UNCONFIGURED_VALUE showing up as the value of a non-existent Optional<String> injection point when the configuration value was missing when running under wildfly swarm 2018.3.3.

The injection point should be seeing an Optional value for which isPresent is false.

**Comment by jmesnil** [comment]
@starksm64 thanks for the report Scott. I fixed the issue in the implementation with a test in the integration test suite.
